---
apiVersion: v1
kind: Namespace
metadata:
    name: dotnet-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-devops-dotnet
spec:
  replicas: 3 # 3 .NET webapp pods will be created
  selector:
    matchLabels:
      app: oci-devops-dotnet
  template:
    metadata:
      labels:
        app: oci-devops-dotnet
    spec:
      containers:
      - name: oci-devops-dotnet
        image: lhr.ocir.io/apaccpt01/dotnet-webapp:${BUILDRUN_HASH}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocir-secret
---
apiVersion: v1
kind: Service
metadata:
  name: oci-devops-dotnet-service
  labels:
    app: oci-devops-dotnet-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: oci-devops-dotnet