version: 1.0
component: deployment
runAs: root
env:
  variables:
    version: ${BUILDRUN_HASH}
steps:
  # This section is to define the scripts that each step shall run.
  - stepType: Command
    name: stop current running container
    command: docker stop dotnet-webapp
    timeoutInSeconds: 60

  - stepType: Command
    name: remove current running container
    command: docker rm dotnet-webapp
    timeoutInSeconds: 60

  - stepType: Command
    name: login to OCI Container Registry
    command:  docker login syd.ocir.io -u apaccpt01/oracleidentitycloudservice/howie.owi@oracle.com -p "<zxG6}yd1ZP9:bqm48Fk"
    timeoutInSeconds: 60

  - stepType: Command
    name: run the latest image
    command: docker run -dit -p 8080:80 --name dotnet-webapp syd.ocir.io/apaccpt01/dotnet-webapp-repo:${version}
    timeoutInSeconds: 60

  - stepType: Command
    name: check the running container
    command: docker ps
    timeoutInSeconds: 60

  - stepType: Command
    name: completed
    command: echo "deployment completed"
    timeoutInSeconds: 60