version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:5.0
  oci-executor:
    docker:
      - image: ghcr.io/oracle/oci-cli:latest
    environment:
      OCI_CLI_FINGERPRINT: $OCI_CLI_FINGERPRINT
      OCI_CLI_KEY_CONTENT: $OCI_CLI_KEY_CONTENT
      OCI_CLI_REGION: $OCI_CLI_REGION
      OCI_CLI_TENANCY: $OCI_CLI_TENANCY
      OCI_CLI_USER: $OCI_CLI_USER

jobs:
  build:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Build the project
          working_directory: dotnetwebapp/
          command: dotnet publish --configuration Release --output ./publish
      - persist_to_workspace:
          root: dotnetwebapp/publish
          paths:
            - .
      # - run:
      #     name: Run tests
      #     working_directory: dotnetwebapp/
      #     command: dotnet test --no-restore --verbosity normal

  build_docker: 

  deploy:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Deploy to server
          command: |
            scp -r ./publish user@yourserver:/path/to/deploy
            ssh user@yourserver 'sudo systemctl restart your-dotnet-app'

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build