version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
  oci-executor:
    docker:
      - image: ghcr.io/oracle/oci-cli:latest
  base-executor:
    docker:
      - image: cimg/base:2025.02

jobs:
  build_dotnet_app:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Build .NET Core app
          command: |
            cd dotnetwebapp
            dotnet publish --configuration Release
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_docker:
    executor: base-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t syd.ocir.io/apaccpt01/dotnet-webapp-repo:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image to OCI Container Registry
          command: |
            docker login -u "$OCIR_USER" -p "$OCIR_PASSWORD" syd.ocir.io
            docker push syd.ocir.io/apaccpt01/dotnet-webapp-repo:${CIRCLE_SHA1}

  deploy:
    executor: oci-executor
    steps:
      - checkout
      - run:
          name: Deploy app to OCI using OCI DevOps
          command: |
            export OCI_CLI_KEY_CONTENT=$(echo "$OCI_CLI_KEY_CONTENT" | base64 -d)
            oci devops deployment create-pipeline-deployment --pipeline-id $OCI_DEVOPS_PIPELINE_ID --deployment-arguments "{\"items\":[{\"name\":\"BUILDRUN_HASH\",\"value\":\"${CIRCLE_SHA1}\"}]}"

workflows:
  build_and_deploy:
    jobs:
      - build_dotnet_app
      - build_docker:
          requires: 
            - build_dotnet_app
      - deploy:
          requires:
            - build_docker