version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
  oci-executor:
    docker:
      - image: ghcr.io/oracle/oci-cli:latest
    # environment:
    #   OCI_CLI_FINGERPRINT: $OCI_CLI_FINGERPRINT
    #   OCI_CLI_KEY_CONTENT: $OCI_CLI_KEY_CONTENT
    #   OCI_CLI_REGION: $OCI_CLI_REGION
    #   OCI_CLI_TENANCY: $OCI_CLI_TENANCY
    #   OCI_CLI_USER: $OCI_CLI_USER
  base-executor:
    docker:
      - image: cimg/base:2025.02

jobs:
  # build:
  #   executor: dotnet-executor
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build the project
  #         command: |
  #           cd dotnetwebapp
  #           dotnet publish --configuration Release
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .

  # build_docker:
  #   executor: base-executor
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run:
  #         name: Build Docker image
  #         command: |
  #           docker build -t syd.ocir.io/apaccpt01/dotnet-webapp-repo:${CIRCLE_SHA1} .
  #     - run:
  #         name: Push Docker image
  #         command: |
  #           docker login -u "$OCIR_USER" -p "$OCIR_PASSWORD" syd.ocir.io
  #           docker push syd.ocir.io/apaccpt01/dotnet-webapp-repo:${CIRCLE_SHA1}

  deploy:
    executor: oci-executor
    steps:
      - checkout
      - run:
          name: Check OCI CLI
          command: |
            rm ~/.oci/config
            -d os ns get

workflows:
  build_and_deploy:
    jobs:
      - deploy
      # - build
      # - build_docker:
      #     requires: 
      #       - build
      # - deploy:
      #     requires:
      #       - build_docker